package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;

public class FXMLMainController {
	@FXML
	private Label lblTitle;
	@FXML
	private Button btnChange;
	@FXML
	private Button btnReset;

	// Event Listener on Button[#btnChange].onAction
	@FXML
	public void btnChange(ActionEvent event) {
		Stage mainWindow = (Stage)lblTitle.getScene().getWindow();
		String title = lblTitle.getText();
		mainWindow.setTitle(title);
	}
	// Event Listener on Button[#btnReset].onAction
	@FXML
	public void btnReset(ActionEvent event) {
		// TODO Autogenerated
	}
}
